Refactor edition
cabinet/cabinet-cli pull request #11
Opened 2017-04-16 04:39 UTC by facundovictor

- Update the util function "get_content_from_editor" to be able to
load the item content to the editor if any.
- Update the cabinet wrapper by adding the function "get_item_content".
This function allows to get the items content without printing anything
to the stdout unless there is some error.
- Remove the -u option from the subcommand "add". Updating should
have its own subcommand.
- Add the subcommand "edit" with support for loading the current item content
within the default editor.

2017-04-16 22:18 UTC, ivanalejandro0 requested changes
Cool, I was waiting for a separation between `add`/`update` :).

Regarding the update, if the user doesn't specify tags when updates the contents, the tags are cleared up. We should preserve the existing tags if no `--tag` switch is used.
We also should allow the user to update only the tags and leave the content as it is, but let's tackle that in a different PR :)

Regarding docstrings, we should document using python's types like `str` or `dict` instead of `String` or `Dictionary`, it has the same informative value and uses the exact expected type name.

2017-04-16 22:18 UTC, ivanalejandro0 commented on cli.py
> +    """Add an item to cabinet"""
copy/paste leftover :) ... this is for edit/update.

2017-04-17 03:51 UTC, facundovictor commented on cli.py
> +    """Add an item to cabinet"""
Ops.. yes.. copy/paste. Fixing right away!

2017-04-17 03:57 UTC, facundovictor commented
Thanks for the review!!! =D
Regarding how we should handle updating tags, yes, we should discuss different approaches and it should be addressed in a different PR.
For now, I've updated the docstrings for using the python's types. And, I've updated the description of the sub-command "update".

2017-04-17 22:58 UTC, ivanalejandro0 approved these changes

2017-04-17 22:59 UTC, merged